spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresTwo
    username: postgres
    password: 10051996Al
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080

jwt:
  secret: afe7738d20228729185cd3d4092a7ec1b4fedb56
  lifetime: 30m

#  docker:
#    compose:
#      file: ./docker-compose.yml
#      enabled: true
#      lifecycle-management: start_and_stop